#!/bin/bash

echo "installing Apache Ignite"

sudo bash -c 'cat <<EOF > /etc/yum.repos.d/ignite.repo
[ignite]
name=Apache Ignite
baseurl=http://apache.org/dist/ignite/rpm/
gpgcheck=1
repo_gpgcheck=1
gpgkey=http://apache.org/dist/ignite/KEYS
       http://bintray.com/user/downloadSubjectPublicKey?username=bintray
EOF'
sudo yum -y check-update
sudo yum -y install apache-ignite

sudo cp /etc/apache-ignite/default-config.xml /etc/apache-ignite/config.xml

sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 47500:47509 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 47400 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 47100 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 47101 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 48100 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 48101 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 31100 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 31101 -j ACCEPT

echo "Done - Apache Ignite..."